//YOU ARE GIVEN AN ARRAY OF INTEGER NUMS, THERE IS A SLIDING WINDOW OF SIZE k WHICH IS MOVING FROM THE VERY LEFT OF THE ARRAY TO THE VERY RIGHT. YOU CAN ONLY SEE THE k NUMBERS IN THE WINDOWS. EACH TIME THE SLIDING WINDOW MOVES RIGHT BY ONE POSITION. RETURN THE MAX SLIDING WINDOW WHICH BASICALLY CONTAINS THE MAX ELEMENT IN EACH WINDOW
//LEETCODE QUESTION 239

}