//FUNCTIOONS
// #include <iostream>
// using namespace std;
// bool Prime(int n){
//     if(n<2){
//         return false;
//     }
//     for(int i=2;i<n;i++){
//         if(n%i==0){
//             return false;
//         }
//     }
//     return true;

// }
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     cout<<Prime(n);
// }


// #include <iostream>
// using namespace std;
// bool Prime(int n=3){        //DEFALUT PARAMETER INT N=3 
//     if(n<2){
//         return 0;
//     }
//     for(int i=2;i<n;i++){
//         if(n%i==0){
//             return 0;
//         }
//     }
//     return 1;

// }
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     cout<<Prime();
// }