//OPERATOR 
//ARITHEMATIC OPERATOR +,-,/,%,*,++,--
// #include <iostream>
// using namespace std;
// int main(){
//     int a=10;
//     //cout<<a++;   //PREINCREAMENT
//     cout<<++a;   //POSTINCREAMENT
// }



//COMPARISON OPR -->>       >,<,>=,<=,==,!=


//LOGICAL OPR -->>>   &,|,^,<<,>>
#include <iostream>
using namespace std;
int main(){
    int a=2;
    int b=3;
    int c=a&b;
    cout<<c;
    cout<<endl;
    int d=a|b;
    cout<<d;
    cout<<"\n";
    int e=6<<2;   //NUMBER*2^X  HERE NUMBER=6 X=2
    cout<<e;
    cout<<"\n";
    int f=6>>2;
    cout<<f;
}