//Q1-->>> ADD DIGITS 
//https://leetcode.com/problems/add-digits/submissions/1655440130/

//Q2--->>> LEAP YEAR
//https://www.geeksforgeeks.org/problems/leap-year0943/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab


//Q3--->>> REVERSE AN INTEGER
//https://leetcode.com/problems/reverse-integer/description/




//IMP//Q4 --->> POWER OF TWO 
//https://leetcode.com/problems/power-of-two/description/


//IMP  //Q5--->> SQRT(X)

//https://leetcode.com/problems/sqrtx/description/


//Q6 --->> PALLINDORME NUMBER
//https://leetcode.com/problems/palindrome-number/description/


//Q7 -->> COMPLIMENET OF BASE 10
//https://leetcode.com/problems/complement-of-base-10-integer/description/

//Q8 -->> UGLY NUMBER

//https://leetcode.com/problems/ugly-number/description/


//Q9 --->> SQUARE N*N IN A CHESS  BOARD

//https://www.geeksforgeeks.org/problems/squares-in-nn-chessboard1801/1?page=1&difficulty%255B%255D=-1&category%255B%255D=Numbers&sortBy=submissions
