// Q1
// 1: Take a number n from the user and print all the even numbers between 1 and n(inclusive). Do this using while and do while loop separately.
// #include <iostream>
// using namespace std;
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     int i=1;
//     while(i<=n){
//         cout<<i<<" ";
//         i++;
//     }
// }


// #include <iostream>
// using namespace std;
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     int i=1;
//     do{
//         cout<<i<<" ";
//         i++;
//     }
//     while(i<=n);
// }