// 2: Find the factorial of a number n using a while loop and do a while loop.

// #include <iostream>
// using namespace std;
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     int pro=1;
//     int i=1;
//     while(i<=n){
//         pro=pro*i;
//         i++;
//     }
//     cout<<"The factorial of "<<n<<" is: "<<pro;
// }


// #include <iostream>
// using namespace std;
// int main(){
//     int n;
//     cout<<"Enter the value of n: ";
//     cin>>n;
//     int pro=1;
//     int i=1;
//     do{
//         pro=pro*i;
//         i++;
//     }
//     while(i<=n);
//     cout<<"The factorial of "<<n<<" is: "<<pro;
// }